config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    resources :reviews, except: [:show, :index]
  end

  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: { medium: "400x700>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :movies
  has_many :reviews, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :avg_rating, only: [:show]
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:image, :title, :description, :rating, :user_id)
    end

    def avg_rating
      if @movie.reviews.blank?
        @avg_rating = 0
      else
        @avg_rating = @movie.reviews.average(:rating).round(2)
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_movie
  # before_action :set_average_rating
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @movie.id }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @movie.id, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie.id }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="../,,/../public/stylesheet.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!-- Navbar content -->
  <div style="background-color: #e3f2fd;">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/">MovieApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </div>



  <body>
    <%= yield %>
  </body>

  <p>Made with Love E></p>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
  <div class="text-center">
    <% if current_user %>
      <p> <%= "Welcome #{current_user.name}!" %>
      </p><br>
        <%= link_to(destroy_user_session_path, method: :delete) do %>
          <h3 class="btn btn-primary"> Log Out
          </h3>
        <% end %>
    <% else %>
      <h3> <%= link_to "Login to add a movie or to leave a review", new_user_session_path %>
      </h3>
    <% end %>
  </div>

  <br>

<div class="wrapper">
 <div class="container">
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-md-4">
        <strong>
          <h2><%= movie.title %></h2>
        </strong>
        <%= image_tag(movie.image.url(:medium), size: "240x270") %>
        <strong>
          <h3> Rating: <%= movie.reviews.average(:rating).round(2) unless movie.reviews.blank?%></h3>
        </strong>
        <%= link_to(movie_path(movie.id)) do%>
          <h3 class="btn btn-lg btn-primary"> Read More </h3>
        <% end %>
        </div>
      <% end %>
    </row>
  </div>
</div>

  <br>
  <div class="wrapper">
    <div class="container">
      <% if current_user %>
        <%= link_to(new_movie_path) do %>
          <div class="text-center">
            <div class="btn btn-lg btn-primary"> Add New Movie</div>
          </div>
        <% end %>
      <% else %>
      <%= link_to(new_user_registration_path) do  %>
      <div class="text-center">
        <div class="btn btn-lg btn-primary"> Sign up</div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="wrapper show">
  <div class="row">
    <div class="col-md-6">
      <p>
        <%= image_tag(@movie.image.url(:medium), size: "400x400") %>
      </p>
      <p>
        <strong>Title:</strong>
        <%= @movie.title %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @movie.description %>
      </p>

      <p>
        <strong>Rating:</strong>
        <%= @avg_rating %>
      </p>

      <p>
        <strong>Created By:</strong>
        <%= @movie.user.name %>
      </p>
    </div>
  </div>
</div>

<% if current_user %>
<div class="wrapper">
<%= link_to("Add a Review", new_movie_review_path(@movie.id), class: "btn btn-primary")  %>
</div>
<% end %>

<div class="wrapper">
<% @movie.reviews.each do |review| %>
<div class="row">
<%= review.rating %><br>
<%= review.comment %><br>
</div>
<% end %>
</div>


<div class="wrapper">
<% if current_user %>
  <% if @movie.user_id == current_user.id %>
    <%= link_to(edit_movie_path(@movie)) do %>
      <div class="btn btn-danger">Edit</div>
    <% end %>
      </div>

    <%= link_to(@movie, method: :delete, data: { confirm: 'Are you sure?' }) do%>
     <div class="btn btn-danger">Delete Movie</div>
    <% end %>
  <% end %>
</div>
<% end %>


<div class="wrapper">
<div class="btn btn-lg btn-primary">
    <%= link_to(movies_path) do %>
      <div class="color-white">Back</div>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', movie_review_path %></td>
        <td><%= link_to 'Edit', edit_movie_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_movie_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', movies_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>